services:
  web:
    container_name: webapp
    restart: unless-stopped
    build:
      context: ./webapp
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - POSTGRES_DB=search-engine
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - HF_HOME=/root/hugging_face
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./webapp/app:/app/app
      - ./webapp/hugging_face:/root/hugging_face
      - ./webapp/cache:/app/cache
      - ./webapp/frontend:/app/frontend
      - ./webapp/logs:/app/logs
      - ./assets:/app/assets:ro
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - postgres
  
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: search-engine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./assets/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"